.\" Manpage for fortibackup.
.TH NAPI-BASH 1 "2013-09-02" "0.1" "fortibackup"
.SH NAZWA
fortibackup - backup konfiguracji fortigate.
.SH SKŁADNIA
fortibackup [opcje]
.br
fortibackup <-h|--help>
.SH OPIS
fortibackup - Pozwala na opbranie konfugoracji fortigate na lokalny dysk. Możliwość uruchomienia programu w cronie pozwala na automatyczne wersjonowanie historii konfiguracji.
.SH OPCJE
.SS -h, --help, --usage
Wyświetl pomoc
.SH BŁĘDY
Znalazłaś/eś jakiś błąd - wypełnij formularz dostępny na stronie projektu.
.SH ZOBACZ TEŻ
.BR fortibackup (5)
.SH AUTOR
Grzegorz (grzew) Wieczorek - grzewster@gmail.com
.PP
Strona projektu: https://github.com/grzew/fortibackup
.PP
.B Program został wykonany przy użyciu tych narzędzi:
    ruby
.fi

